include: https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml

variables:
  JULIA_CUDA_VERBOSE: 'true'
  JULIA_NUM_THREADS: 8

.base:
  extends:
    - .julia:1.5
    - .test
  tags:
    - nvidia
    - fastcpu

test-GPU:
  extends: .base
  variables:
    GROUP: GPU
    DATADEPS_ALWAYS_ACCEPT: 'true'
