# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 1
# matrix:
#  allow_failures:
#    - julia: nightly
notifications:
  email: false
script: 
  - julia -e 'using Pkg; pkg"registry add https://github.com/HolyLab/HolyLabRegistry.git"'
  - julia -e 'using Pkg; Pkg.test("DiffEqFlux"; coverage = true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("DiffEqFlux")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("DiffEqFlux")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
